language: node_js
node_js:
  - "stable"

sudo: false

notifications:
  email: false

cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - npm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
